language: node_js
node_js:
  - "6"

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
  - npm install -g npm@3

install:
  - cd ~/build/northwesternmutual/ai-challenge/algorithmService && npm install
  - cd ~/build/northwesternmutual/ai-challenge/simulatorService && npm install
  - cd ~/build/northwesternmutual/ai-challenge/tournamentService && npm install

script:
  - cd ~/build/northwesternmutual/ai-challenge/algorithmService && npm test
  - cd ~/build/northwesternmutual/ai-challenge/simulatorService && npm test
  - cd ~/build/northwesternmutual/ai-challenge/tournamentService && npm test

  