language: node_js
node_js:
  - "node"

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
  - npm install -g npm@3

install:
  - cd TRAVIS_BUILD_DIR/algorithmService && npm install
  - cd TRAVIS_BUILD_DIR/simulatorService && npm install
  - cd TRAVIS_BUILD_DIR/tournamentService && npm install

script:
  - cd TRAVIS_BUILD_DIR/algorithmService && npm test
  - cd TRAVIS_BUILD_DIR/simulatorService && npm test
  - cd TRAVIS_BUILD_DIR/tournamentService && npm test

  