language: node_js
node_js:
  - "node"

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
  - npm install -g npm@3

install:
  - cd ~/algorithmService && npm install
  - cd ~/simulatorService && npm install
  - cd ~/tournamentService && npm install

script:
  - cd ~/algorithmService && npm test
  - cd ~/simulatorService && npm test
  - cd ~/tournamentService && npm test

  