language: node_js
node_js:
  - "6"

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
  - npm install -g npm@3

install:
  - cd ~/build/northwesternmutual/ai-challenge && npm install

script:
  - cd ~/build/northwesternmutual/ai-challenge && npm test
