language: node_js
node_js:
  - "6"

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

install:
  - cd ~/build/northwesternmutual/ai-challenge && npm install
  - cd ~/build/northwesternmutual/ai-challenge && npm run build

script:
  - cd ~/build/northwesternmutual/ai-challenge && npm test
  - cd ~/build/northwesternmutual/ai-challenge && npm run lint
  - cd ~/build/northwesternmutual/ai-challenge && npm run coverage

after_success:
  - cd ~/build/northwesternmutual/ai-challenge && npm run coveralls
