language: node_js

node_js:
  - "6"

sudo: required

services:
  - docker

env:
  global:
    - secure: "BsfBcR8JVeWYwdYtk6Wia3tgEjoc8b/4cr0gnsKIoyR3f6FdmAPNrY+ai/49NdsZMvPShBm0ToJxiP1fZEuQ7Ol9OfgcA7bU96kq7eQyT48yrPtx6X/SCStIWVUW6qMjHd8psVh4aRtZegY89cyJgFinMEaePRb3+O7skMxbT2B1WigkRMzWEC2H6o3tGrrEKcGx25/wMzOEOR2rZXW07qMqtnj8ZyG4y3MCNJWu968nN7DUm2TXTMcKIpiTAi4jgm6z5/7UTXhakOQFAQsrcw4tmxy46s4cdoimE4KUJ8vMl+zNXAMacJHYc475AXJjQMxhmZWaWql0oJYbOvSQdQONGAxitHui8cKhDTaPw1LiOW06NQmtK2vdG3ZTMv/V+Ma6IVGbNgrkvsDTFqielcjEYabRJ7oA/5g3jPHv0hrIecJk7aTqoALQ5bDi3UdzfJ0Mpu6FZx4Mnj2FnY7T7/gg7msIVRusSskrGzEAnO1vdcE1ezUxCHM8rY4Rdp/nSLhGvRDbDm6flmARX/xyzvISYlYwDlQxTnjzJyGElJk8BW+3gOY5ArrYw+z0aMjcvaI3mrSkHenZH2yVW6zH2YLcoaafl7JobIkgO+Eoam8zGCVm/7K79XGsyLO3ELETHab8+Xj/QRBNN4/ZHHZPHiGD5RgIjgPZu+S+1RBbNYc="
    - secure: "Dq0Ei7VZWVfXCOUjeVIDaAtDmj5c3QbEYbS15JgVFHPzK4MxcJTklF2gH2E+cwn29tlUi+ZiVrIPayOer8ULXD6GgWpVFtxKwnZXCb2LL0GiO9omM3Pam/P04qbueWOB2bpJ3hfIZiQLa/UWBqIC+3YVHPFB7oUwpNOoT353VW3gvYMMCCW6QT2+NcvefXuMST4M8OKord79E7M/CLdjNT8yx2F2zTmLJRoqtB+FMpDsuY+3W3QQRC0Nx0qxq6xRYrCpUjFa/hqWMAzW4D73XNqz/T0m2iR0XL02FYjjuOBccN02m8ZFmv4jtmuSvHxEkDsYPrLy+2Nb+HBq3mGq+t9h4DajRVE+yWaqKkurR9bAWvhXtZL98ncgZ4gPJnRzwsP5CDTlq4SsXBIWW1QRfMoWT9WuIAGVxvdGWBcy1GyjRlbkpIUAYD9Egvky2c/y9eeDw5TwuUDdHQGAFOfE4QT4OhMYs+UTJ8dL7Q7JmZgmm2Rk3K3fQ/OvO39zlcY0OS54NqnIsxuyyZEUoFEqDX1yvOCexFds4y1fkZv+zhI+OxD2YliwjP4qFUqa4RR8LKt/+CNOED1VMOdlZuYvzOxFGn1yzBPqPP06hXe2krSuvQO5Vrba9e1KcH+3N06myvDN7m8UOOoBflNaVd/XtRfO6NMzMvc8yQfd2L32RE8="
    - secure: "kX4L18fOvho+sdZFTZtYmA2AZXjD8/6YxckSQwIsIhex9fjEv1yal1MeUTsufSrKlSo+64sa0agpYQwlDbXfoVho7e3MM7SXTcB0QEQbv/oEY4DIZBYg5pbx99mpAsx6TkMqWomlOJE9eJDx7SrJnGFWfPbEQkDXgtQOLfw6T/BlDfZ79d+f0VOr58RmDczDq7lKLDL74cwyzk1jFww8jCEnaQYJ/yD19eNDLTQtzIRixjg35bNLMcWwgQYllfwECmfDbVbqSaddIZi9Pn8XEYZjNU8x+gPEzLGi+K63nzSI6q893RTPK4IWNBT/ycdQ1pgoijVYGScAZWQqx3oN+0DfDoZ8Wfl3yjQkYJsmk+ZvzUrjhpNuB3wCv0McQGnzNjEMFwnrNqcOF4PTVaeYv8kTyO4AvVcfzPy/aG1V9CCZgcHKUZhV9wKnW4NpfIHVvFmoAHn0XouejTP6y+0ShOb4UEKu5Ei95wXuLG9uZmXINhDwUIKHCLR6UrWIi5T2L//Fe5FX8rA5XT8GahA/8bjZss7gVaPsDTWU8IS0NYesl9VlZMjwvw06pJyqZsPqD6RbOxRUVhSj3N5Zrlb/8ZE8U50Z0dZZukY691kBu6IF1850P6IH4hq2rh3qv+3LIBHZ6sQI3XF9ytDxZ7JP+We/cDWA0o6ZfM6eCYVdHEI="
    - COMMIT=${TRAVIS_COMMIT::8}
    - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
  - echo $DOCKER_USER
  - echo $DOCKER_PASS
  - echo $DOCKER_EMAIL

install:
  - cd ~/build/northwesternmutual/ai-challenge && npm install
  - cd ~/build/northwesternmutual/ai-challenge && npm run build

script:
  - cd ~/build/northwesternmutual/ai-challenge && npm test
  - cd ~/build/northwesternmutual/ai-challenge && npm run lint
  - cd ~/build/northwesternmutual/ai-challenge && npm run coverage

after_success:
  - cd ~/build/northwesternmutual/ai-challenge && npm run coveralls
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t northwesternmutual/aichallenge-algorithm:$COMMIT ~/build/northwesternmutual/ai-challenge/algorithmService/
  - docker tag northwesternmutual/aichallenge-algorithm:$COMMIT northwesternmutual/aichallenge-algorithm:$TAG
  - docker tag northwesternmutual/aichallenge-algorithm:$COMMIT northwesternmutual/aichallenge-algorithm:travis-$TRAVIS_BUILD_NUMBER
  - docker push northwesternmutual/aichallenge-algorithm
