language: node_js
node_js:
  - "6"

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
  - npm install -g npm@3

install:
  - cd ~/build/northwesternmutual/ai-challenge && npm install

script:
  - cd ~/build/northwesternmutual/ai-challenge && npm test
  - cd ~/build/northwesternmutual/ai-challenge && npm run lint
  - cd ~/build/northwesternmutual/ai-challenge && npm run coverage

after_success:
  - cd ~/build/northwesternmutual/ai-challenge && npm run coveralls
