# instrumentation:
#     root: .
#     extensions:
#         - .js
#     default-excludes: true
#     excludes: ["*-spec.js", "**/mock/**", "algorithmService/mock/*.js", "simulatorService/mock/*", "tournamentService/mock/*"]