---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: mongodb
  name: mongodb
  namespace: ai-challenge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
          protocol: TCP

---

kind: Service
apiVersion: v1
metadata:
  labels:
    app: mongodb
  name: mongodb
  namespace: ai-challenge
spec:
  type: ClusterIP
  ports:
  - port: 27017
  selector:
    app: mongodb

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: algorithm
  name: algorithm
  namespace: ai-challenge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: algorithm
  template:
    metadata:
      labels:
        app: algorithm
    spec:
      containers:
      - name: algorithm
        image: northwesternmutual/kubernetes-algorithm
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP

---

kind: Service
apiVersion: v1
metadata:
  labels:
    app: algorithm
  name: algorithm
  namespace: ai-challenge
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: algorithm

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: simulator
  name: simulator
  namespace: ai-challenge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simulator
  template:
    metadata:
      labels:
        app: simulator
    spec:
      containers:
      - name: simulator
        image: northwesternmutual/kubernetes-simulator
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP

---

kind: Service
apiVersion: v1
metadata:
  labels:
    app: simulator
  name: simulator
  namespace: ai-challenge
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: simulator

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: tournament
  name: tournament
  namespace: ai-challenge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tournament
  template:
    metadata:
      labels:
        app: tournament
    spec:
      containers:
      - name: tournament
        image: northwesternmutual/kubernetes-tournament
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP

---

kind: Service
apiVersion: v1
metadata:
  labels:
    app: tournament
  name: tournament
  namespace: ai-challenge
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: tournament

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: ai-challenge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: northwesternmutual/kubernetes-nginx
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP

---

kind: Service
apiVersion: v1
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: ai-challenge
spec:
  type: NodePort
  ports:
  - port: 80
  selector:
    app: nginx
          