swagger: '2.0'

info:
  version: 1.0.0
  title: Simulation Service
  description: Performs a simulation of two AI implementations
  
basePath: /

consumes:
  - application/json

produces:
  - application/json
  
schemes:
  - http
  - https

paths:
  /simulation:
    get:
      description: Get all `Algorithms` in the database
      parameters:
        - $ref: "#/parameters/collection"
        - $ref: "#/parameters/algorithmOne"
        - $ref: "#/parameters/algorithmTwo"
        - $ref: "#/parameters/simulations"
      responses:
        200:
          description: Successful response
          schema:
            $ref: "#/definitions/result"
        400:
          description: No `Algorithms` in the database
        500:
          description: Databse error
      
definitions:
  result:
    type: object
    required: [first, last, placeShips, shoot, email]
    properties:
      _id:
        description: The ID of the `Algorithm`
        type: string
      first:
        description: The first name associated with the `Algorithm`
        type: string
      last:
        description: The last name associated with the  `Algorithm`
        type: string
      placeShips:
        description: The algorithm for placing ships
        type: string
      shoot:
        description: The algorithm for shooting
        type: string
      email:
        description: The email associated with the  `Algorithm`
        type: string
      wins:
        description: The number of wins the `Algorithm` has
        type: string
      losses:
        description: The number of losses the `Algorithm` has
        type: string
        
parameters:
  algorithmOne:
    name: algorithmOne
    description: the id of algorithm one
    in: query
    required: true
    type: integer
    
  algorithmTwo:
    name: algorithmTwo
    description: the id of algorithm two
    in: query
    required: true
    type: integer
    
  simulations:
    name: simulations
    description: the number of simulations to run
    in: query
    required: true
    type: integer
    
  collection:
    name: collection
    description: the collection that the algorithms belong to
    in: query
    required: true
    type: string